[project]
name = "try-event-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "q_log @ file:///G:/z/工具/python环境/python_whl/q_log-0.1.1-py3-none-any.whl ; sys_platform=='win32'",
    "numpy>=2.4.2",
    "redis>=7.1.0",
    "pyzmq>=26.4.0",
]
